### ISSUE TITLE
Anyone know the exact Fauxbar frequency scoring options to get as close to the Firefox awesome bar as possible?

### ISSUE THREAD

**Issue by JeffKang** [ChrisNZL/Fauxbar#1] opened 2016-02-05 02:56 UTC
I personally can’t figure out the frequency settings yet.
I want history items to go to the top after only a few revisits.

Also, if you select in Firefox something after typing “res”, I think that it gets a bonus for other shorter searches.
If I then type “re”, it’s more likely to appear because I selected it after typing “res”.
After selecting an item after using “re”, it’s more likely to appear in the list that comes after typing “r”.

I made it so that there are 30 results.
After I press one letter, an item shows up at #28.
I repeatedly press the letter, select the item, close the tab, press the letter, select the item, close the tab, in the history item never rises to the top like in the Firefox awesome bar.

**Comment by JonasNo** [comment] 2016-04-08 09:10
I assume this is you too:
https://www.reddit.com/r/fauxbar/comments/4492ba/anyone_know_the_exact_fauxbar_frequency_scoring/

I've compared the default values in Fauxbar with the ones in Firefox.
'Sampled Visits', 'Bucket Weights' and 'Bucket Cutoffs' are all equal.

The 'Transition Bonuses' that match the ones in Firefox are all equal.

However there's a catch. Chrome do not have the same behavior as Firefox when it comes to the 'Transition Bonuses'. This can cause inconsistencies.
I vaguely remember having issues with this when I rewrote Fauxbar from scratch for fun. Can't check that code. Sadly that code is on a hard drive that may be lost. It is a hybrid drive and the SSD part started to fail. I need a dual drive docking station for SATA laptop and desktop drive to try and recover the data and clone it to a new drive and a new hard drive to clone it to. Anyway...

At the time I found it was nearly impossible to compensate for the difference in behavior. I did file a few bug reports since I found bugs in what transition type was used and such. As usual the bug reports was ignored. Typical of Chrome development team. This was a few months ago to some years. Don't know if they ever did anything about those bugs.

I have not done any tests for if I can write some code for Fauxbar that can compensate for this since your description lacks details and precise steps of how to reproduce your issue from a clean profile and the steps you took in Firefox (assuming clean profile).

**Comment by ChrisNZL** [comment] 2016-04-08 09:42
Hi guys. Fauxbar dev here.

One thing that might affect the result placement is if Chrome's URL prefetch is getting triggered, which might be affecting what you're expecting? You can disable the setting in Fauxbar to not use it; maybe it would have some effect.

Unless I overlooked something at the time, I think my interpretation of the frecency algorithm was good enough at least; results seemed to be high enough as expected. I did have an idea to perhaps allow the user to right-click on a result and choose "Increase this result's frecency score" just to help make a result always appear at the top for you, but never got around to implementing it.

From memory, I made favorites have a slightly higher value than what the original frecency algorithm; a personal preference I guess.

There's also the case that Fauxbar doesn't automatically degrade saved values over time automatically like Firefox does, since I don't have a service running now and then to do that, nor did I want to force the user sit through the reindexing process without their consent. So sites that you used to visit lots but never visit anymore; their values will always remain higher unless you force Fauxbar to reindex.

I should probably fix the HTML5 notification errors that Fauxbar throws when it first starts.

Admittedly, years ago, I lost interest in maintaining Fauxbar when Google would change their APIs. Got tired of playing whack-a-mole to fix things. The final straw was when Chrome removed the ability to let New Tab Pages focus the Omnibox; I devised the "close the tab then create a new tab that I can actually steal focus from" method, but to this day I'm still not happy with it.

I'm also not happy with Chrome how, if you press **F**+**Space**, enter your search query and select a result, how the caret keeps blinking; really annoying.

But yeah, lost so much interest that I let the fauxbar.org domain lapse. Stopped checking the gmail account for bug reports. Looking back, I was suffering from depression which didn't help things. So it just sort of sat there. And then Google announced they were closing Google Code down, so I thought I ought to at least preserve the code and copy it over here to GitHub.

Also at the time, Chrome did not allow developers to monetise extensions, and my Donate button was scarcely used. Being compensated for time and effort is nice, but that wasn't really available at the time... And feature creep seemed to be getting the better of me. Bug reports. Requests. I was sick of it all. So throw in all these factors and my attitude toward the project, I just left it alone.

But, I dunno. Times change. I still use Fauxbar. Depression's gone. My motivation is with other things though. Perhaps I'll fix up the couple of notification bugs that get thrown. Apart from checking the URL prefetching, not sure what else to suggest.

**Closed** 2017-01-14 03:46 UTC
