### ISSUE TITLE
SQL database error: "could not execute statement (778 disk I/O error)"

### ISSUE THREAD

**Issue by fhoshino** [ChrisNZL/Fauxbar#12] opened 2017-02-05 04:33 UTC
Does not seems to affect usability.

![chrome_2017-02-05_12-31-51](https://cloud.githubusercontent.com/assets/771955/22623719/35b57c3e-eb9f-11e6-8c0a-1bf66f1dccb7.png)

**Comment by ChrisNZL** [comment] 2017-02-05 06:00
The lines mentioned are used with `chrome.history.onVisited` and `chrome.tabs.onUpdated` which are super common as you browse the web and use Chrome. If it's only happened a couple times, I assume the disk I/O error is an issue with Chrome, possibly a file-locking issue, something that Fauxbar has no control over.

Please try:
- Restarting Chrome
- Restarting your computer

Does this resolve the issue?

**Comment by fhoshino** [comment] 2017-02-05 06:04
Seems not, does this affects on massive page loads?

**Comment by ChrisNZL** [comment] 2017-02-05 06:10
I've no idea. I've tried reproducing this issue by opening lots of pages and at once but no luck. An I/O error sounds like an issue with Chrome, perhaps the WebSQL database file that Chrome has stored for Fauxbar is getting locked for some reason.

If the issue persists after restarting your computer, I'd suggest uninstalling Fauxbar and reinstalling Fauxbar, just so Chrome can wipe the extension's files completely. If you want to backup your options first, check Fauxbar's Options > Management section for backup instructions.

**Comment by fhoshino** [comment] 2017-02-05 06:11
Will close this first, and let me observe for a while.

**Comment by fhoshino** [comment] 2017-02-05 16:18
Reopen as restarting machine and reinstall extension does not help.
![2017-02-06_00-17-20](https://cloud.githubusercontent.com/assets/771955/22627645/a871b3c0-ec01-11e6-8a18-fd58ea470edd.png)

**Comment by ChrisNZL** [comment] 2017-02-05 19:37
Investigating further, error 778 is [SQLITE_IOERR_WRITE](https://www.sqlite.org/rescode.html#ioerr_write).

Searching around, a few pages regarding this with Chrome suggest this error is caused if a harddrive is almost full. Is your harddrive almost out of space?

These aren't strictly related to Chrome extensions but sound similar:

- https://bugs.chromium.org/p/chromium/issues/detail?id=408743#c2
- https://bugs.chromium.org/p/chromium/issues/detail?id=430518#c16
- https://bbs.archlinux.org/viewtopic.php?pid=1143205#p1143205

I found that Fauxbar's SQLite file (a file named as a number without an extension) is located within:

C:\Users\YOUR_USERNAME\AppData\Local\Google\Chrome\User Data\Default\databases\chrome-extension_hibkhcnpkakjniplpfblaoikiggkopka_0

For me, the file was about 15 MB, but then I reinstalled Fauxbar and it was about 6 MB. In my code I've written Fauxbar's database quota as 100 MB, though I've just tried setting the quota to 1 MB and it didn't make a difference (I guess Chrome overrides this and gives it an unlimited quota).

Comments linked above suggest issues were arising if their drives were almost full, so maybe try clearing some space? Other than that, I'm out of ideas.

**Comment by fhoshino** [comment] 2017-02-05 19:42
My db is 3MB in size and my disk has 90G free space out of 240G, which is nowhere near full.

**Comment by ChrisNZL** [comment] 2017-02-05 19:45
Does Fauxbar's background console have any info? To view:

1. Go to chrome://extensions
2. Click to developer mode checkbox
3. Under Fauxbar, click the background page link

**Comment by fhoshino** [comment] 2017-02-06 03:56
![chrome_2017-02-06_11-55-52](https://cloud.githubusercontent.com/assets/771955/22634301/53af45ca-ec63-11e6-9fd8-8fed53a1b8e8.png)

**Comment by fhoshino** [comment] 2017-02-07 17:58
Errors on line: 646, 681, 754, 1641 of js/background-new.js

**Comment by ChrisNZL** [comment] 2017-02-09 06:59
> Unchecked runtime.lastError while running tabs.captureVisibleTab: Failed to capture tab: unknown error

Unknown errors - dunno. Probably an issue with Chrome that's out of my control.

>Errors on line: 646, 681, 754, 1641 of js/background-new.js

What are the accompanying error messages? Can you screenshot the log again?

**Comment by fhoshino** [comment] 2017-02-09 07:04
![chrome_2017-02-09_15-03-45](https://cloud.githubusercontent.com/assets/771955/22772662/03529226-eed9-11e6-81ea-2e6f38ef3b4a.png)

**Comment by ChrisNZL** [comment] 2017-04-19 00:19
Closing this.
I/O errors are out of Fauxbar's control, likely due to issues with Chrome, user's harddrive, or operating system issues.

**Closed by ChrisNZL** 2017-04-19 00:19 UTC
