### ISSUE TITLE
Fauxbar Corrupting 

### ISSUE THREAD

**Issue by herocrow** [ChrisNZL/Fauxbar#51] opened 2019-08-11 16:43 UTC
After a few days my fauxbar corrupts and then I have to repair it and set my website list all over again. This happens after 3 days and I do not know what the cause of it is. This issue only happens with fauxbar and not fauxbar lite.

**Comment by ChrisNZL** [comment] 2019-08-11 20:59
Thanks for reporting this.
Sounds like a dupe of issue #50. Please subscribe there for updates.

**Closed as completed by ChrisNZL** 2019-08-11 20:59 UTC
Labels: duplicate
