### ISSUE TITLE
Feature request: add keyword to open all bookmarks in a folder

### ISSUE THREAD

**Issue by fhoshino** [ChrisNZL/Fauxbar#26] opened 2017-08-14 11:27 UTC
i.e. using a keyword would load all the bookmarks in a folder in tabs.

**Comment by ChrisNZL** [comment] 2017-12-05 01:00
Duplicate of Issue #14 

I've partially got bookmark folder searching working but have been hitting some snags.

I'll try to return to this later for v1.8.0.

**Closed by ChrisNZL** 2017-12-05 01:00 UTC
Labels: duplicate
